#!/bin/bash -eu

mkdir "$STAGING_DIR"/quickstart

cp quickstart/*.json "$STAGING_DIR/quickstart/"

gzip -c -d \
  quickstart/wikiticker-2015-09-12-sampled.json.gz > \
  "$STAGING_DIR/quickstart/wikiticker-2015-09-12-sampled.json"
